/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * API version: 1.21
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Not found
type GetCharactersCharacterIdCalendarEventIdAttendeesNotFound struct {
	// Not found message
	Error_ string `json:"error,omitempty"`
}
